[package]
name = "z0ne"
version = "0.1.0"
authors = ["Kura <me@kurabloodlust.eu>"]
edition = "2018"

[dependencies]
tracing-subscriber = "0.2"
tracing-appender = "0.1"
tracing = "0.1"
log = "0.4"
snafu = "0.6"
dotenv = "0.15"